version: "2"
checks:
  file-lines:
    config:
      threshold: 1000
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 250
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
exclude_patterns:
  - "example/"
  - "**/test.js"
